# 环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat 最大线程数，默认为200
      max: 800
      # tomcat 启动初始化的线程数，默认值10
      min-spare: 100

# Spring 配置
spring:
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tang-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: Tang
  # Redis 配置
  data:
    redis:
      password:

# MyBatis 配置
mybatis:
    # 搜索指定包别名
    # typeAliasesPackage: com.tang.**.entity
    # 配置 mapper 的扫描，找到所有的 mapper.xml 映射文件
    mapper-locations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    # configLocation: classpath:mybatis/mybatis-config.xml

# 接口文档配置
springdoc:
  swagger-ui:
    # 是否开启
    enabled: true
    # 访问路径
    path: /api-docs

# 日志配置
logging:
  level:
    org:
      springframework: warn
    com:
      tang: debug
  pattern:
    dateformat: HH:mm:ss.SSS

# token 配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥 Create by https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx 256-bit with Hex
  secret: 556A586E3272357538782F413F4428472D4B6150645367566B59703373367639
  # 时间颗粒度
  time-unit: minutes
  # 令牌有效期
  expire-time: 30
